---
- name: Install Node Exporter on RedHat
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Install Node Exporter on Ubuntu/Debian
  include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"
