---
- name: Create node exporter user
  user:
    name: node_exporter
    system: yes
    shell: /usr/sbin/nologin

- name: Download Node Exporter archive
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Extract Node Exporter binary
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      - --strip-components=1
    creates: /usr/local/bin/node_exporter

- name: Ensure Node Exporter binary is executable
  file:
    path: /usr/local/bin/node_exporter
    mode: '0755'

- name: Create systemd service
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
  notify: restart node exporter