plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  instance-state-name: running
  tag:Project: oneclick-monitoring

keyed_groups:
  - key: tags.Role
    prefix: "_"

hostnames:
  - instance-id

compose:
  ansible_user: root
  ansible_connection: amazon.aws.aws_ssm
  ansible_python_interpreter: /usr/bin/python3
