- name: Install packages
  apt:
    name:
      - nginx
      - curl
    update_cache: yes
    state: present

# Web content

- name: Copy HTML page
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: "0644"

# Nginx site

- name: Deploy nginx site config
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/web_app
    mode: "0644"
  notify: restart nginx

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/web_app
    dest: /etc/nginx/sites-enabled/web_app
    state: link
  notify: restart nginx


- name: Remove default nginx site
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  notify: restart nginx


# Start nginx

- name: Ensure nginx is enabled and running
  systemd:
    name: nginx
    enabled: yes
    state: restarted

# Health check

- name: Wait for nginx_status endpoint
  uri:
    url: "http://127.0.0.1:{{ web_port | default(80) }}/nginx_status"
    status_code: 200
  register: nginx_status_check
  retries: 10
  delay: 3
  until: nginx_status_check.status == 200

# Nginx Prometheus Exporter

- name: Download nginx exporter
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_linux_amd64.tar.gz
    dest: /tmp/nginx-exporter.tar.gz
    mode: "0644"

- name: Extract nginx exporter
  unarchive:
    src: /tmp/nginx-exporter.tar.gz
    dest: /tmp
    remote_src: yes
    creates: /tmp/nginx-prometheus-exporter

- name: Install nginx exporter binary
  copy:
    src: /tmp/nginx-prometheus-exporter
    dest: /usr/local/bin/nginx-prometheus-exporter
    mode: "0755"
    remote_src: yes

# Systemd service for nginx exporter
- name: Create nginx exporter service
  copy:
    dest: /etc/systemd/system/nginx-exporter.service
    mode: "0644"
    content: |
      [Unit]
      Description=Nginx Prometheus Exporter
      After=nginx.service network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/nginx-prometheus-exporter \
        -web.listen-address=:9113 \
        -nginx.scrape-uri=http://127.0.0.1/nginx_status
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and restart nginx exporter
  systemd:
    name: nginx-exporter
    enabled: yes
    state: restarted