galaxy_info:
  author: Mukesh Kharb
  description: Deploys Prometheus, Grafana, Node Exporter, and NGINX with a basic web page on Debian and RedHat systems.
  company: Personal/Organization Name

  license: MIT
  min_ansible_version: '2.9'

  galaxy_tags:
    - prometheus
    - grafana
    - node_exporter
    - monitoring
    - systemd
    - devops

dependencies: []
