---
- name: Configure Monitoring Stack
  hosts: _monitoring
  become: true
  become_user: root
  gather_facts: true
  
  pre_tasks:
    - name: Fetch ALB DNS from SSM
      set_fact:
        alb_dns: "{{ lookup('amazon.aws.ssm_parameter',
                            '/monitoring/alb_dns',
                            region='ap-south-1') }}"

  roles:
    - prometheus
    - grafana
    - blackbox
    - node_exporter
    - web_app
