---
- name: Configure Monitoring Stack
  hosts: _monitoring
  become: true
  become_user: root
  gather_facts: true
  roles:
    - prometheus
    - grafana
    - blackbox
    - node_exporter
    - app_server
