---
- name: Setup k3s server and monitoring
  hosts: k3s_server
  gather_facts: false
  vars:
    ansible_connection: amazon.aws.aws_ssm
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml
    monitoring_namespace: monitoring
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - k3s_install
    - monitoring_k8s
