---
- name: Setup k3s server and monitoring
  hosts: _k3s_server
  gather_facts: false

  vars:
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml
    monitoring_namespace: monitoring

  roles:
    - k3s_install
    - monitoring_k8s
