---
- name: Install packages on Debian/Ubuntu
  apt:
    name:
      - python3
      - openjdk-11-jdk
      - maven
      - git
      - unzip
      - wget
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Enable extras repo for Maven (Amazon Linux)
  command: amazon-linux-extras enable java-openjdk11
  when: ansible_distribution == "Amazon"
  changed_when: false

- name: Install packages on RedHat/Amazon Linux
  yum:
    name:
      - python3
      - java-11-openjdk
      - git
      - unzip
      - wget
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Maven via EPEL (Amazon Linux)
  yum:
    name: maven
    state: present
  when: ansible_distribution == "Amazon"
