---
- name: Install k3s
  shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  become: true

- name: Enable and start k3s
  systemd:
    name: k3s
    enabled: true
    state: started
  become: true

- name: Wait for kubeconfig
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    timeout: 60
  become: true
