pipeline {
  agent any

  environment {
    AWS_DEFAULT_REGION = 'ap-south-1'
    TF_IN_AUTOMATION   = 'true'
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'mukesh',
            url: 'https://github.com/478mkharb/Ansible.git'
      }
    }

    stage('Terraform Init & Apply') {
      steps {
        dir('oneclick-monitoring-VPC-end/terraform') {
          sh '''
            terraform init -input=false
            terraform apply -auto-approve -input=false
          '''
        }
      }
    }

    stage('Wait for SSM Managed Instances') {
      steps {
        sh '''
          EXPECTED=2
          echo "Waiting for monitoring EC2 instances to be ONLINE in SSM..."

          for i in {1..30}; do
            ONLINE=$(aws ssm describe-instance-information \
              --filters "Key=tag:Project,Values=oneclick-monitoring" \
              --query "length(InstanceInformationList[?PingStatus=='Online'])" \
              --output text)

            if [ "$ONLINE" -eq "$EXPECTED" ]; then
              echo "All monitoring EC2 instances are ONLINE in SSM"
              exit 0
            fi

            echo "$ONLINE / $EXPECTED instances online. Waiting..."
            sleep 30
          done

          echo "Monitoring EC2 instances did not become ONLINE in time"
          exit 1
        '''
      }
    }

    stage('Run Ansible (via SSM)') {
      steps {
        dir('oneclick-monitoring-VPC-end/ansible') {
          sh '''
            export PATH=$PATH:/var/lib/jenkins/.local/bin

            ansible-galaxy collection install amazon.aws --force

            ansible-inventory -i inventory/aws_ec2.yml --graph

            ansible-playbook -i inventory/aws_ec2.yml site.yml
          '''
        }
      }
    }
  }
}
