- name: Render Thanos objstore config
  ansible.builtin.template:
    src: objstore.yml.j2
    dest: /tmp/objstore.yml
    mode: "0644"
  become: true

- name: Create / update Thanos objstore secret
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

    kubectl -n monitoring delete secret thanos-objstore --ignore-not-found

    kubectl -n monitoring create secret generic thanos-objstore \
      --from-file=objstore.yml=/tmp/objstore.yml
  args:
    executable: /bin/bash
  become: true

